options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🚢 Build the Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '-f', './NutritionAmbition.Backend.API/Dockerfile', '.']

  # 🚀 Push the Docker Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']

  # 🚀 Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/$PROJECT_ID/backend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--timeout=300s'  # Extended timeout
      - '--set-secrets=OpenAiSettings__ApiKey=OpenAiApiKey__ApiKey:latest'
      - '--set-secrets=OpenAiSettings__AssistantId=OpenAiApiKey__AssistantId:latest'
